### ISSUE TITLE
Windows binaries for V2.1.0

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTs#155]
@ntustison @stnava @dorianps could you please help me by providing Windows binaries for v2.1.0, please see github releases webpage, select edit release and upload the binary. https://github.com/stnava/ANTs/releases I have already uploaded Linux binaries, and just compiled OS X.

**Comment by ntustison** [comment]
Thanks for all the work @armaneshaghi.  Unfortunately, I don't have a windows machine and I'm pretty sure Brian doesn't either.

**Comment by armaneshaghi** [comment]
I think @dorianps was the person Brian suggested.

**Comment by stnava** [comment]
Yes.... @dorianps will be able to put something together from his windows
machine.

**Comment by dorianps** [comment]
An update on the Windows binaries:
There is something that doesn't when trying to compile 2.1.0 source files with Visual Studio.
"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1."

The error occurs always in the same spot each time I try changing options (i.e. zlib etc). The old code from November works fine. I will try to find where is the problem, but if someone has an idea what has changed, please let me know.

Here is the build output:
https://www.dropbox.com/s/1pm1zwqfdz3umv8/BuildFailureANTs210Windows.txt?dl=1

**Comment by armaneshaghi** [comment]
any updates on this? I'm sorry that I can't help with windows.

**Comment by dorianps** [comment]
Unfortunately the only update is that it's not working yet.  I tried
several options and to localize the problem but couldn't find it yet. There
seem to be something related to CustomBuild rules and I see that a lot of
things have changed from the version I last tried in November. Will look
more when I have some time.  Meanwhile, if some one has an idea what might
have changed to cause the issue, please let me know.

Dorian

**Comment by stnava** [comment]
maybe this

8>  CMake Error at CMake/ProjectSourceVersion.cmake:38 (include):
8>    include could not find load file:
8>
8>      C:/Users/DP/Desktop/ANTs210/CMake/ProjectSourceVersionVars.cmake
8>  Call Stack (most recent call first):
8>    Version.cmake:17 (include)
8>    ANTS.cmake:16 (include)
8>    CMakeLists.txt:57 (include)
8>
8>
8>  -- Building ANTS version "2.1.0-gGITDIR-NOTFOUND"


brian

**Comment by dorianps** [comment]
Ok, I managed to compile the Windows binaries and everything is now in the release page. Hope all is good there, open to suggestions otherwise.

Now let's turn to the problem that was causing the issue. It appears something was wrong with:
CMake/ProjectSourceVersionVars.cmake

The file didn't seem to be there at all, there was ProjectSourceVersionVars.cmake.in instead. So I just added a copy without .in

Another problem that might be that in ProjectSourceVersion.cmake line 38 is
  include( "${CMAKE_CURRENT_SOURCE_DIR}/CMake/ProjectSourceVersionVars.cmake" )
You might want to check whether this is correct because my build worked only after adding another mirror folder called CMake/CMake with same files. The few times my build failed it seemed that was searching one more folder CMake (but who knows, I might be wrong).

Last, the errors that come out of the entire build are related to examples. I am not sure how important are these, perhaps it prevents running the tests. What is important for me is that we got the binaries.

FYI, there has been a couple of places in France and Germany that are using Windows builds for their work, so it's working ok. But I think a comparison of results between platforms would be better to make sure that we are all talking apples.

These are the example errors I mentioned:

Error	178	error C2057: expected constant expression [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	45	1	ANTS
Error	179	error C2466: cannot allocate an array of constant size 0 [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	45	1	ANTS
Error	180	error C2133: 'sigma' : unknown size [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	45	1	ANTS
Error	181	error C2057: expected constant expression [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	119	1	ANTS
Error	182	error C2466: cannot allocate an array of constant size 0 [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	119	1	ANTS
Error	183	error C2133: 'sigma' : unknown size [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	119	1	ANTS
Error	227	error C2057: expected constant expression [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	45	1	ANTS
Error	228	error C2466: cannot allocate an array of constant size 0 [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	45	1	ANTS
Error	229	error C2133: 'sigma' : unknown size [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	45	1	ANTS
Error	230	error C2057: expected constant expression [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	119	1	ANTS
Error	231	error C2466: cannot allocate an array of constant size 0 [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	119	1	ANTS
Error	232	error C2133: 'sigma' : unknown size [C:\Users\DP\Desktop\ANTs210binary\ANTS-build\Examples\l_antsSliceRegularizedRegistration.vcxproj]	c:\users\dp\desktop\ants210\examples\make_interpolator_snip.tmpl	119	1	ANTS

**Comment by stnava** [comment]
Does the same issue occur with the current github version of ants ?

**Comment by dorianps** [comment]
Will try. I sticked to 2.1.0 to stay in line with builds.

**Comment by dorianps** [comment]
Indeed, the file CMake/ProjectSourceVersionVars.cmake is missing. The build
failed again with the latest ANTs. But it worked when I created the missing
file from the same file ending in .cmake.in. So binaries are produced
successfully. The examples still fail as before.

Dorian

**Comment by armaneshaghi** [comment]
Thanks @dorianps I will close this.

**Comment by abizeau** [comment]
Thanks, I had the same problem. This isn't fix yet. Just copy-paste the file and remove .in extension and ANTS-configure works.

**Comment by MarcCote** [comment]
I used the tarball from http://stnava.github.io/ANTs/ and got the same issue. Copy-pasting the file `CMake/ProjectSourceVersionVars.cmake.in` and removing the `.in` extension did the trick. ANTS-configure works, now.
