### ISSUE TITLE
enable COPY_SCRIPTS_TO_BIN by default in compilation 

### ISSUE THREAD

**Issue by stnava** [stnava/ANTs#2]

**Comment by ntustison** [comment]
Okay, I think I fixed this.  See here

https://github.com/stnava/ANTs/blob/master/Examples/CMakeLists.txt#L203-L217

I had to copy the scripts twice because people could select to install based on a relative path or to the default /usr/bin (on mac).  We might need to revisit if we find a better cmake variable which points to ultimate install directory.
