### ISSUE TITLE
Inverse transform

### ISSUE THREAD

**Issue by rshkarin** [stnava/ANTs#223]
Hello,

I have found transformation `Image1 -> Image2` and got `Image1_transformed`, then how can I transform `Image1_transformed` to `Image1`?

Thanks!

**Comment by ntustison** [comment]
What exactly did you do to find the transformation ``Image1 -> Image2``?

**Comment by rshkarin** [comment]
I have executed:

```
antsRegistration --dimensionality 3 --float 0 --output [ImageTransform,Image1Warped.nii.gz,Image1InverseWarped.nii.gz] 
--interpolation BSpline --use-histogram-matching 0 --initial-moving-transform [Image2.nii,Image1.nii,1] 
--transform Rigid[0.1] --metric MI[Image2.nii,Image1.nii,1,32,Regular,0.25] --convergence [1000x500x400x250x100,1e-6,10] --shrink-factors 16x12x8x4x2 --smoothing-sigmas 5x4x3x2x1vox 
--transform Affine[0.1] --metric MI[Image2.nii,Image1.nii,1,32,Regular,0.25] --convergence [1000x500x400x250x100,1e-6,10] --shrink-factors 16x12x8x4x2 --smoothing-sigmas 5x4x3x2x1vox
```

That's I have somehow transformed `Image1` to `Image2` and got `Image1_transformed`, and now I want to recover the initial alignment of `Image1`, using the `Image1_transformed`.

**Comment by ntustison** [comment]
In addition to the transform ``ImageTransform0GenericAffine.mat``, you should also have two warped images:  ``Image1Warped.nii.gz`` and ``Image1InverseWarped.nii.gz``.  The former is the moving image warped to the space of the fixed image and the latter is the fixed image warped to the space of the moving image.

**Comment by rshkarin** [comment]
Yes, I have it, but how I can recover initial alignment of `Image1` using these warped images and transformation file?

**Comment by ntustison** [comment]
I don't understand what you're asking.  Could you elaborate further?

**Comment by stnava** [comment]
the initialization is determined by the header.

you can see the overlap using a tool like itk snap.


brian

**Comment by rshkarin** [comment]
So, I have several data sets, each ~30Gb.

I want to perform a rigid registration to the template data set for each one. 
As far as I know, I can't perform registration of a such big data (due to ITK restrictions), so I will scale them to the appropriate size and then perform the registration.

When all data sets will be registered to the template, I will perform segmentation of some parts of these data sets using SyN (the template data set is already segmented).

When I will get the segmentations of all interesting data sets, then I want to transform them to the initial positions of the data sets used in the segmentation process.

Finally, when the segmentations will have "the initial positions", I will scale it back to the original size to get the segmentations of the original full size data sets.

Thanks!

**Comment by ntustison** [comment]
The affine and rigid registrations will transform the images correctly regardless of whether they're the full size or the resampled size as long as you did the resampling correctly to maintain the header information.

**Comment by ntustison** [comment]
"affine and rigid registrations" should be "affine and rigid transforms"

**Comment by rshkarin** [comment]
Thank you! But, nevertheless, how can I transform the  segmentations to "the initial position"? I found the way of applying the transformations to the other data sets, but how to take inverse transformation, unfortunately I didn't find.

Actually, I am interesting in this step:

> When I will get the segmentations of all interesting data sets, then I want to transform them to the initial positions of the data sets used in the segmentation process.

Sorry if I am asking something stupid, just I am struggling with it the last couple of days.

**Comment by cookpa** [comment]
Are you asking how to apply an inverse of an affine transform?

If you did

antsRegistration --dimensionality 3 --float 0 --output [ImageTransform,Image1Warped.nii.gz,Image1InverseWarped.nii.gz] 
--interpolation BSpline --use-histogram-matching 0 --initial-moving-transform [Image2.nii,Image1.nii,1] 
--transform Rigid[0.1] --metric MI[Image2.nii,Image1.nii,1,32,Regular,0.25] --convergence [1000x500x400x250x100,1e-6,10] --shrink-factors 16x12x8x4x2 --smoothing-sigmas 5x4x3x2x1vox 
--transform Affine[0.1] --metric MI[Image2.nii,Image1.nii,1,32,Regular,0.25] --convergence [1000x500x400x250x100,1e-6,10] --shrink-factors 16x12x8x4x2 --smoothing-sigmas 5x4x3x2x1vox


and you have a segmentation of Image2, then you should be able to do


  antsApplyTransforms -d 3 -r Image1.nii -t [ ImageTransform0GenericAffine.mat, 1] -n NearestNeighbor -i Segmentation.nii -o segmentationDeformedToImage1.nii


the transform [ Affine.mat, 1 ] implies inverse of the transform since you are warping from "Fixed" to "Moving" space. If you were going in the other direction you'd do


  -r Image2.nii -t ImageTransform0GenericAffine.mat

**Comment by rshkarin** [comment]
@cookpa Thank you! That is exactly what I was looking for!
