### ISSUE TITLE
DGM segmentation failure

### ISSUE THREAD

**Issue by armaneshaghi** [stnava/ANTs#255]
Dear @ntustison and @stnava 

I have had this problem for a while where `Atropos` segmentation fails for deep grey matter (please see the attached picture). I have put a reproducible example with the code at this address: https://github.com/armaneshaghi/atropos_failure 
   
    Atropos -d 2 -a template.nii.gz -i PriorProbabilityImages[4,prior0%d_smoothed.nii.gz,0.25] -c [3,0] -o [output_segk.nii.gz,output_prob%0d.nii.gz] -m [0.1,1x1x1] -x brain_mask.nii.gz

![atropos_fail](https://cloud.githubusercontent.com/assets/4290297/11374379/b4d458ae-92cd-11e5-91f9-adb3c71e87b5.png)

Any help is appreciated.

**Comment by stnava** [comment]
Can you clarify what you mean by failure? It looks to me like you have not
succeeded with the brain extraction but I am just guessing and  cannot run
your example simply because I don't have time at the moment.

One critical consideration is whether your priors are actually zero outside
the deep gray matter. If they are not then you should 0 them out.

**Comment by armaneshaghi** [comment]
Thanks , thresholding priors solves the issue.
