### ISSUE TITLE
Inputs do not occupy the same physical space! 

### ISSUE THREAD

**Issue by khamael** [stnava/ANTs#261]
I'm a bit confused, the issues with ITK are fixed or not? 

terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/ubuntu/src/SuperBuild_ANTS-Sandbox/ITKv4-install/include/ITK-4.9/itkImageToImageFilter.hxx:248:
itk::ERROR: LabelStatisticsImageFilter(0x3e43b30): Inputs do not occupy the same physical space! 
InputImage Origin: [-1.3625800e+02, -1.1759302e+02, -5.8974091e+01], InputImage_1 Origin: [-1.3625800e+02, -1.1759302e+02, -5.8974094e+01]
	Tolerance: 5.2730006e-07

**Comment by ntustison** [comment]
I have not encountered any appearances of this exception since the fix was provided in ITK. Your machine might continue to have issues but, unless we can characterize this problem as something that exists beyond your specific machine, we do not have any plans to investigate this issue further.  See [here](https://github.com/stnava/ANTs/issues/74) for ways to address it on your machine.

**Comment by khamael** [comment]
That's why I thought it is weird, as I've cloned and freshly built it. The ITK fix should be part of it right?
I'm investigating it further. Thanks

**Comment by ntustison** [comment]
That would be great if you could investigate further.  The ITK superbuild should include the fix.  In fact, the current ITK should have been updated multiple times since the fix in question.

**Comment by cookpa** [comment]
I think the fix prevented images in the same physical space from drifting out of alignment internally. For example, you could run antsRegistration and it would work fine for a few iterations and then throw this error. I've not seen that happen since the ITK fix.

As far as I know, there are still precision issues with I/O, at least to NIFTI headers. See here

https://github.com/stnava/ANTs/issues/74#issuecomment-130852531

for an example. This can cause the error to arise if you have many layers of processing on derived images. I work around this by using the same reference image wherever possible.

**Comment by stnava** [comment]
CopyImageHeaderInformation


brian
