### ISSUE TITLE
Image not aligning properly

### ISSUE THREAD

**Issue by gitmegit** [stnava/ANTs#364]
I tried to align images with
./antsRegistrationSyNQuick.sh -d 2 -f /home/gamaliel/Patient3/Patient3_Baseline_PA.dcm -m /home/gamaliel/Patient3/Patient3_Postop1_AP.dcm -o outputImage 

The output images did not align with the baseline.  I have attached jpg versions of the starting images and the output in the order of image to move, warped image and baseline or fixed image. 

![patient3_postop1_ap](https://cloud.githubusercontent.com/assets/22177698/18889706/270fb7d8-84cc-11e6-8353-4e359961ccfd.jpg)
![outputimagewarped](https://cloud.githubusercontent.com/assets/22177698/18889707/27115d22-84cc-11e6-8ddc-5f89d7887b15.jpg)
![patient3_baseline_pa](https://cloud.githubusercontent.com/assets/22177698/18889705/270c63bc-84cc-11e6-88ab-4307446f8edb.jpg)

I tried to do the alignment with just affine to see if that would be better by editing antsRegistrationSynQuick as follows

COMMAND="${ANTS} --verbose 1 \
               ...
to

COMMAND="${ANTS} --verbose 1 \
                        --t a
              ,,,,
but that gave a segmentation fault.

**Comment by ntustison** [comment]
You don't need to edit the internals of ``antsRegistrationSyNQuick.sh``.  You simple do 

```
./antsRegistrationSyNQuick.sh -d 2 -f /home/gamaliel/Patient3/Patient3_Baseline_PA.dcm -m /home/gamaliel/Patient3/Patient3_Postop1_AP.dcm -o outputImage -t a
```

**Comment by stnava** [comment]
this example along with [this recent mouse example](https://sourceforge.net/p/advants/discussion/840261/thread/c00c0ef3/?limit%3D25%233990&source=gmail&ust=1475089817590000&usg=AFQjCNGizhCnWXTdg-3WtkQoOIVN1pRXww) are good examples of two cases where the assumption of a generic registration algorithm are challenged by different degrees of mismatch.

in the current (lung) case, we have substantial non-corresponding structure due to the fact that the images are projection images collected with different patient orientation etcetera.  there is also substantial structure that is presumbly *not* of interest.  the standard approach for solving these types of problems is to do some preprocessing to extract the lungs or key landmark points that highlight the features of interest.  then perform registration on whatever is the relevant result from that pre-processing.    e.g. the lung boundaries or whatever.  i cant think of an off the shelf solution for this particular case (off hand) but am sure that a little work (even just within the domain of ants or antsr) would uncover something that would work.

in the mouse example, the **basic medical image registration assumption that there is close to one to one (diffeomorphic) correspondence** is much closer to being satisfied.  however, the researcher is noting that the articulated structures ( the limbs ) are not matching well.  we might recommend a similar approach as above but using a stage-wise approach.   register the subjects together automatically.  then use some prior spatial knowledge to automatically identify the articulated structures.  then register these individually by running per-limb focused registrations.  this is a little bit complicated but can be achieved fairly easily with ants initialization and masking functionality.  we also have multiple metrics that could do something similar ... note that i dont think the timevaryingvelocityfield is really the right thing here.   the issue is that the articulated structures have their own (local) rigid motion relative to the body.  this is why i am recommending a piecewise approach. 

hope this helps.

**Comment by stnava** [comment]
i referred another user to this answer and thus reopened (probably temporarily).

**Comment by gitmegit** [comment]
The other responses were not important.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by NathanCho** [comment]
Thanks for the comments! I was wondering whether TimeVaryingVelocityField indeed works for mouse whole body registration with articulated joints (limbs). Your recommendation using a stage-wise approach totally makes sense to me.

**Comment by stnava** [comment]
it would work (but so would syn) with the right (piecewise) initialization / feature set.   same for the lung example.
