### ISSUE TITLE
BSplineSyn allow more deformation

### ISSUE THREAD

**Issue by spinicist** [stnava/ANTs#385]
Hello,
I am still registering my pre-clinical (mouse/rat) brains. I have one dataset where I am getting good results in the cerebrum, but the cerebellums aren't as good as I would like.

I am currently using `BSplineSyN[0.1,1.5,0,3]` as my transform settings. For the `updateFieldMeshSizeAtBaseLevel` parameter I started with 2.6 - I copied 26 from the defaults, and divided by 10 because rat brains are approximately a factor of 10 smaller in each dimension. I then reduced this to 1.5 hoping that might allow more deformation in the cerebellum, but it made no visible difference to the result. Should I have increased it instead?

Are there any other settings to try? Am I misunderstanding how the regularization works (probably)?

**Comment by ntustison** [comment]
When you specify a knot spacing of 2.6 mm or 1.5 mm, a mesh size is estimated using that knot spacing with the constraint that the B-spline domain must extend over the entire image domain.  That might be one factor as to why the regularization is not changing.  The print out to the screen prior to the B-spline SyN stage should indicate the mesh size that is actually being used based on your knot spacing.   You could use that information to force a decrease in regularization by increasing the mesh size on the command line, i.e. ``BSplineSyN[0.1,10x10x10,0,3]``.  

Also, since it's the cerebellum, make sure that you have enough background between any objects of interest and the image boundary as there's a fixed boundary condition with the diffeomorphic transforms.

**Comment by spinicist** [comment]
Thanks Nick - I had spotted the print out of the mesh size but didn't know what it meant. I will try putting in slightly larger numbers and see what happens.

With regard to your second point, does applying a mask affect where the boundary condition is applied? I have noticed subtle but important differences in registration when using a fixed image mask compared to having no mask.

**Comment by ntustison** [comment]
> With regard to your second point, does applying a mask affect where the boundary condition is applied? I have noticed subtle but important differences in registration when using a fixed image mask compared to having no mask.

No, a mask doesn't affect the application of the boundary condition which is always fixed at the bounds of image domain.  However, there will be subtle differences when a mask is provided in B-spline SyN and original SyN given that the former uses a fitting routine for smoothing (which can incorporate a mask) whereas the latter smooths the update and/or total fields via convolution.
